### ISSUE TITLE
报错，求助

### ISSUE THREAD

**Issue by xiao-chopin** [whenfung/simple#13]
╰─ jekyll server --watch                                      ─╯
Configuration file: /home/github/simple/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-feed or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the jekyll-feed gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- jekyll-feed' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
                    ------------------------------------------------
      Jekyll 4.2.2   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
/var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/external.rb:73:in `rescue in block in require_with_graceful_fail': jekyll-feed (Jekyll::Errors::MissingDependencyException)
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/external.rb:58:in `block in require_with_graceful_fail'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/external.rb:57:in `each'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/external.rb:57:in `require_with_graceful_fail'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/plugin_manager.rb:30:in `require_gems'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/plugin_manager.rb:22:in `conscientious_require'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:131:in `setup'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:36:in `initialize'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:30:in `new'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:30:in `process'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /var/lib/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /var/lib/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /var/lib/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /var/lib/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /var/lib/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bin/jekyll:25:in `load'
        from /usr/local/bin/jekyll:25:in `<main>'
/var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/external.rb:60:in `require': cannot load such file -- jekyll-feed (LoadError)
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/external.rb:60:in `block in require_with_graceful_fail'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/external.rb:57:in `each'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/external.rb:57:in `require_with_graceful_fail'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/plugin_manager.rb:30:in `require_gems'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/plugin_manager.rb:22:in `conscientious_require'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:131:in `setup'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:36:in `initialize'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:30:in `new'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:30:in `process'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /var/lib/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /var/lib/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /var/lib/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /var/lib/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /var/lib/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /var/lib/gems/3.0.0/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bin/jekyll:25:in `load'
        from /usr/local/bin/jekyll:25:in `<main>'

> 

>

**Comment by professordeng** [comment]
_config.yml 中有几个插件本地没有安装，例如 jekyll-feed，你可以百度看看怎么安装，我记得是几个命令，也可以先删去 _config.yml 中相关的几行代码，不影响效果

**Comment by xiao-chopin** [comment]
感谢
